<H1> Lets get started with numpy</H1>


In [1]:
# import your numpy module
import numpy as np

<p dir = 'rtl'>
.קיבלנו קובץ של נתונים המכילים נתונים על בחינות תלמידים במקצוע מדעי המחשב ואנחנו מעונינים לנתח את ההישגים של התלמידים
לשם עליך לפתוח קובץ נתונים השמור בקובץ CSV</br>
ההוראה לפתוח קובץ הוא np.genfromtxt ( '<name of file>', delimiter = ',')
התוצאה תישמר בתוך מערך מסוג numpy
</p>

 <p dir = 'rtl'>
 יחד עם התרגיל הזה, אתם מקבלים קובץ : grades.csv</br>
 פתחו את הקובץ
 </p>

In [ ]:
#open you csv file and print the first 5 rows of the file
arr = np.genfromtxt("grades.csv", delimiter=',')

<p dir = 'rtl'>
הקובץ כפי שהזכרנו קודם, מייצג הישגי תלמידים במספר מבחנים. כל שורה מייצג תלמיד</br>
מצאו כמה תלמידים יש בכיתה ובכמה מקצועות התלמידים נבחנו
</p>

In [ ]:
# print how many students there are 
# print how many exams there were
print(arr.shape[0])
print(arr.shape[1])

36
5


<p dir = 'rtl'>
מצא מה הציון הכי גבוה שכל תלמיד קיבל. </br>
מצא מה הציון הכי נמוך שכל תלמיד קיבל</br>
מצא עבור כל מקצוע מה היה הציון הכי גבוה והכי נמוך
</p>

In [ ]:
#find the greatest grades each student got 
#find the lowest grade each student got
#find the highest grade in each exam
#find the lowest exam
print(np.max(arr,axis=1))
print(np.min(arr,axis=1))

print(np.max(arr,axis=0))
print(np.min(arr,axis=0))

[ 85.  95.  95.  95.  90. 100. 100. 100. 100. 100. 100.  81. 100. 100.
  87. 100. 100. 100. 100. 100.  90.  90. 100. 100.  90. 100. 100.  98.
 100. 100. 100.  98. 100. 100. 100. 100.]
[46. 65. 75. 41. 74. 56. 41. 76. 75. 45. 46. 35. 41. 60. 71. 85. 87. 44.
 78. 70. 51. 57. 70. 47. 59. 79. 71. 75. 65. 68. 71. 74. 77. 75. 80. 86.]
[100. 100. 100. 100. 100.]
[41. 35. 56. 46. 41.]


<p dir = 'rtl'>
כעת מצא את הממוצע הכללי של כל המבחנים</br>
מצא את ממוצע הציונים של כל תלמיד 
ומה הממוצע של כל המבחנים
</p>


In [ ]:
#find avg
print(np.average(arr)) 
print(np.average(arr, axis=0)) # exams
print(np.average(arr, axis=1)) # per student

84.61666666666666
[86.83333333 88.38888889 88.08333333 83.13888889 76.63888889]
[66.6 79.2 83.2 77.8 82.6 85.2 85.2 92.8 91.  89.  82.6 63.8 82.  78.2
 80.6 94.  96.  80.  89.  89.2 76.8 77.6 78.  79.  75.6 90.6 88.2 84.6
 89.6 90.6 93.2 86.8 90.8 90.  92.2 94.6]


<p dir = 'rtl'>
נבחר מקצוע מספר 3 ונתתחיל לבחון אותה </BR>
תחילה נמיין את הציונים במקצוע ונדפיס אותם.</BR>
לאחר מכן, נמצא את החציון של הבחינה. 
</p>

In [21]:
third_exam = arr[:, 3]
third_exam_sorted = np.sort(third_exam)

print(third_exam_sorted)

print(np.median(third_exam_sorted))

[ 46.  67.  70.  70.  75.  75.  75.  77.  80.  80.  80.  80.  80.  80.
  80.  81.  82.  85.  85.  85.  85.  85.  85.  85.  85.  85.  85.  85.
  90.  95.  95. 100. 100. 100. 100. 100.]
85.0


<p dir = 'rtl'>
 קלוט ציון ומצא כמה תלמידים קיבלו מעל הציון הזה בכל מקצוע. </br>
 (רמז: יש הוראה ב- numpy  שנקרא : np.count_nonzero())
 </p>

In [ ]:
g = int(input())

np.count_nonzero(arr > g, axis=0)

array([13, 15, 14,  5,  5])

<p dir = 'rtl'>
לסיכום: מצא את המבחן שבה התלמיד קיבל את הציון הצטיין בה, המקצוע בה התלמידים קיבלו את ציון הכי גבוה</br>
</p>


In [32]:
# find the indices of the subject with the best acheivements and the one most "even"
indices = np.argmax(arr, axis=1)
indices = indices.reshape(-1, 1)
print(indices)

[[4]
 [1]
 [2]
 [2]
 [2]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [4]
 [2]
 [4]
 [0]
 [0]
 [2]
 [0]
 [1]
 [0]
 [4]
 [0]
 [1]
 [0]
 [1]
 [0]
 [4]
 [2]
 [1]
 [0]
 [0]
 [3]
 [0]
 [0]
 [0]
 [1]]
